# Stage 1: Build the Go binary
FROM golang:1.25-trixie as builder

WORKDIR /app

# Copy go.mod and go.sum to download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the worker3 binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/worker3 ./cmd/worker3

# Stage 2: Create the final image
FROM alpine:latest

WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/worker3 .

# Run the binary
CMD ["./worker3"]
